#!/bin/bash

# Script to verify and fix SMTP settings in Supabase

echo "🔍 Verifying SMTP Configuration..."
echo "=================================="
echo ""
echo "Current Configuration:"
echo "- Host: smtp.resend.com"
echo "- Port: 465 (SSL)"
echo "- Username: resend"
echo "- Password: re_gf9oScbs_EaxNpdVffGKZxbNgWYrNUUkx"
echo ""
echo "📋 Troubleshooting Steps:"
echo ""
echo "1. Try Alternative Port Configuration:"
echo "   - Change from Port 465 (SSL) to Port 587 (STARTTLS)"
echo "   - This is often more compatible with cloud providers"
echo ""
echo "2. Verify Resend API Key:"
echo "   - Log into https://resend.com/api-keys"
echo "   - Ensure the key has 'sending_access' permission"
echo "   - Try regenerating the key if needed"
echo ""
echo "3. Check Sender Email Domain:"
echo "   - Current: noreply@classboom.vercel.app"
echo "   - Resend may require domain verification"
echo "   - Try using: noreply@resend.dev (Resend's test domain)"
echo ""
echo "4. Manual SMTP Test:"
echo "   You can test SMTP directly with curl:"
echo ""
echo "curl --url 'smtp://smtp.resend.com:587' \\"
echo "  --mail-from 'noreply@resend.dev' \\"
echo "  --mail-rcpt 'your-email@example.com' \\"
echo "  --user 'resend:re_gf9oScbs_EaxNpdVffGKZxbNgWYrNUUkx' \\"
echo "  --upload-file email.txt"
echo ""
echo "5. Alternative: Use Supabase Built-in Email"
echo "   - Temporarily use Supabase's email service"
echo "   - Rate limit: 4 emails/hour (for testing)"
echo "   - Re-enable email confirmations for security"
echo ""
echo "🔧 Recommended Actions:"
echo "1. First, try changing to port 587 in Supabase Dashboard"
echo "2. If that fails, use noreply@resend.dev as sender"
echo "3. Check Resend dashboard for any blocked emails"
echo "4. Consider using Supabase email temporarily"